version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    env_file:
      - ./soar/.env
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
  grafana-data: